# Configuration principale
baseURL = "/"
title = "Ladies of Code Paris"
defaultContentLanguage = "fr"

# Paramètres de base
enableRobotsTXT = true
pagination = { pagerSize = 15 }  # Remplace l'ancien 'paginate'
summaryLength = 0

# Define theme
[module]
  [[module.imports]]
    path = "github.com/jpanther/congo/v2"

# Google Analytics
googleAnalytics = "UA-93698323-1"

# Paramètres du thème
[params]
  # Paramètres d'apparence requis par Congo
  # showAppearanceSwitcher = true
  enableSearch = true
  
  # Votre CSS personnalisé
  customCSS = ["css/compiled/main.css"]

[outputs]
  home = ["HTML", "RSS", "JSON"]

# Configuration du menu (si nécessaire)
[menu]
  [[menu.main]]
    name = "Accueil"
    url = "/"
    weight = 10

[footer]
  showAppearanceSwitcher = true