baseURL = "https://affectionate-hermann-4bed1a.netlify.app/"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "Ladies of Code Paris"
# Main Menu
[[menu.main]]
name = "ðŸ‘©â€ðŸ’»"
url = "#home"
weight = 1
[[menu.main]]
name = "A propos >"
url = "#service"
weight = 2
[[menu.main]]
name = "Actions >"
url = "#resume"
weight = 3
[[menu.main]]
name = "Code de conduite >"
url = "https://github.com/ladiesOfCodeParis/welcome-kit/blob/master/code-of-conduct.md"
weight = 4
[[menu.main]]
name = "Partenaires >"
url = "#partenaires"
weight = 5

# Sitemap Menu
[[menu.sitemap]]
name = "Code de conduite"
url = "https://github.com/ladiesOfCodeParis/welcome-kit/blob/master/code-of-conduct.md"
weight = 1
[[menu.sitemap]]
name = "Rejoindre le slack"
url = "https://forms.gle/xmDBRNckL2KqFFoK8"
weight = 2
[[menu.sitemap]]
name = "Meetup"
url = "https://www.meetup.com/fr-FR/Ladies-of-Code-Paris/events"
weight = 3
[[menu.sitemap]]
name = "Youtube"
url = "https://www.youtube.com/channel/UCJwB6S0vt1Hxjwt2lMMJi0Q/videos"
weight = 4

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright Â© Ladies of Code Paris - Theme by Portio 2020"
footerLogo = "images/site-navigation/logo.png"
# formspreeURL = "YOUR FORMSPREE URL"
googleAnalytics = "UA-93698323-1"
logo = "images/site-navigation/logo.png"

#[params.address]
#address = "23 Khan Niketon, Grand Street, NYK."
email = "paris[at]ladiesofcode.com"
#openingHours = "Open from 10am to 6pm (close at 5pm Sundays)"
#phone = "+(448) 833 5272 332"

#[params.map]
#APIkey = "YOUR GOOGLE MAP API"
#latitude = "23.7783741"
#longitude = "90.3746808"
#pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/LadiesofCodeParis"
weight = 1
# [[params.social]]
# icon = "fa-linkedin-square"
# url = "https://www.linkedin.com/"
# weight = 2
# [[params.social]]
# icon = "fa-pinterest-square"
# url = "https://www.pinterest.com/"
# weight = 3
[[params.social]]
icon = "fa-twitter-square"
url = "https://twitter.com/LadiesCodeParis"
weight = 4
